# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\jcard\OneDrive\Documentos\Programacion\C++\Proyecto_Blackjack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\jcard\OneDrive\Documentos\Programacion\C++\Proyecto_Blackjack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\jcard\OneDrive\Documentos\Programacion\C++\Proyecto_Blackjack\CMakeFiles C:\Users\jcard\OneDrive\Documentos\Programacion\C++\Proyecto_Blackjack\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\jcard\OneDrive\Documentos\Programacion\C++\Proyecto_Blackjack\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Blackjack

# Build rule for target.
Blackjack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Blackjack
.PHONY : Blackjack

# fast build rule for target.
Blackjack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/build
.PHONY : Blackjack/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock_main.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest_main.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Controlador/Controlador.obj: Controlador/Controlador.cpp.obj
.PHONY : Controlador/Controlador.obj

# target to build an object file
Controlador/Controlador.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Controlador/Controlador.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Controlador/Controlador.cpp.obj
.PHONY : Controlador/Controlador.cpp.obj

Controlador/Controlador.i: Controlador/Controlador.cpp.i
.PHONY : Controlador/Controlador.i

# target to preprocess a source file
Controlador/Controlador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Controlador/Controlador.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Controlador/Controlador.cpp.i
.PHONY : Controlador/Controlador.cpp.i

Controlador/Controlador.s: Controlador/Controlador.cpp.s
.PHONY : Controlador/Controlador.s

# target to generate assembly for a file
Controlador/Controlador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Controlador/Controlador.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Controlador/Controlador.cpp.s
.PHONY : Controlador/Controlador.cpp.s

Modelo/Apuesta.obj: Modelo/Apuesta.cpp.obj
.PHONY : Modelo/Apuesta.obj

# target to build an object file
Modelo/Apuesta.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Apuesta.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Apuesta.cpp.obj
.PHONY : Modelo/Apuesta.cpp.obj

Modelo/Apuesta.i: Modelo/Apuesta.cpp.i
.PHONY : Modelo/Apuesta.i

# target to preprocess a source file
Modelo/Apuesta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Apuesta.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Apuesta.cpp.i
.PHONY : Modelo/Apuesta.cpp.i

Modelo/Apuesta.s: Modelo/Apuesta.cpp.s
.PHONY : Modelo/Apuesta.s

# target to generate assembly for a file
Modelo/Apuesta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Apuesta.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Apuesta.cpp.s
.PHONY : Modelo/Apuesta.cpp.s

Modelo/Carta.obj: Modelo/Carta.cpp.obj
.PHONY : Modelo/Carta.obj

# target to build an object file
Modelo/Carta.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Carta.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Carta.cpp.obj
.PHONY : Modelo/Carta.cpp.obj

Modelo/Carta.i: Modelo/Carta.cpp.i
.PHONY : Modelo/Carta.i

# target to preprocess a source file
Modelo/Carta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Carta.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Carta.cpp.i
.PHONY : Modelo/Carta.cpp.i

Modelo/Carta.s: Modelo/Carta.cpp.s
.PHONY : Modelo/Carta.s

# target to generate assembly for a file
Modelo/Carta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Carta.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Carta.cpp.s
.PHONY : Modelo/Carta.cpp.s

Modelo/Crupier.obj: Modelo/Crupier.cpp.obj
.PHONY : Modelo/Crupier.obj

# target to build an object file
Modelo/Crupier.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Crupier.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Crupier.cpp.obj
.PHONY : Modelo/Crupier.cpp.obj

Modelo/Crupier.i: Modelo/Crupier.cpp.i
.PHONY : Modelo/Crupier.i

# target to preprocess a source file
Modelo/Crupier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Crupier.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Crupier.cpp.i
.PHONY : Modelo/Crupier.cpp.i

Modelo/Crupier.s: Modelo/Crupier.cpp.s
.PHONY : Modelo/Crupier.s

# target to generate assembly for a file
Modelo/Crupier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Crupier.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Crupier.cpp.s
.PHONY : Modelo/Crupier.cpp.s

Modelo/Jugador.obj: Modelo/Jugador.cpp.obj
.PHONY : Modelo/Jugador.obj

# target to build an object file
Modelo/Jugador.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Jugador.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Jugador.cpp.obj
.PHONY : Modelo/Jugador.cpp.obj

Modelo/Jugador.i: Modelo/Jugador.cpp.i
.PHONY : Modelo/Jugador.i

# target to preprocess a source file
Modelo/Jugador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Jugador.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Jugador.cpp.i
.PHONY : Modelo/Jugador.cpp.i

Modelo/Jugador.s: Modelo/Jugador.cpp.s
.PHONY : Modelo/Jugador.s

# target to generate assembly for a file
Modelo/Jugador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Jugador.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Jugador.cpp.s
.PHONY : Modelo/Jugador.cpp.s

Modelo/Mazo.obj: Modelo/Mazo.cpp.obj
.PHONY : Modelo/Mazo.obj

# target to build an object file
Modelo/Mazo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Mazo.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Mazo.cpp.obj
.PHONY : Modelo/Mazo.cpp.obj

Modelo/Mazo.i: Modelo/Mazo.cpp.i
.PHONY : Modelo/Mazo.i

# target to preprocess a source file
Modelo/Mazo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Mazo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Mazo.cpp.i
.PHONY : Modelo/Mazo.cpp.i

Modelo/Mazo.s: Modelo/Mazo.cpp.s
.PHONY : Modelo/Mazo.s

# target to generate assembly for a file
Modelo/Mazo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Mazo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Mazo.cpp.s
.PHONY : Modelo/Mazo.cpp.s

Modelo/Participante.obj: Modelo/Participante.cpp.obj
.PHONY : Modelo/Participante.obj

# target to build an object file
Modelo/Participante.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Participante.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Participante.cpp.obj
.PHONY : Modelo/Participante.cpp.obj

Modelo/Participante.i: Modelo/Participante.cpp.i
.PHONY : Modelo/Participante.i

# target to preprocess a source file
Modelo/Participante.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Participante.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Participante.cpp.i
.PHONY : Modelo/Participante.cpp.i

Modelo/Participante.s: Modelo/Participante.cpp.s
.PHONY : Modelo/Participante.s

# target to generate assembly for a file
Modelo/Participante.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/Participante.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/Participante.cpp.s
.PHONY : Modelo/Participante.cpp.s

Modelo/main.obj: Modelo/main.cpp.obj
.PHONY : Modelo/main.obj

# target to build an object file
Modelo/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/main.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/main.cpp.obj
.PHONY : Modelo/main.cpp.obj

Modelo/main.i: Modelo/main.cpp.i
.PHONY : Modelo/main.i

# target to preprocess a source file
Modelo/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/main.cpp.i
.PHONY : Modelo/main.cpp.i

Modelo/main.s: Modelo/main.cpp.s
.PHONY : Modelo/main.s

# target to generate assembly for a file
Modelo/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Modelo/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Modelo/main.cpp.s
.PHONY : Modelo/main.cpp.s

Vista/Vista.obj: Vista/Vista.cpp.obj
.PHONY : Vista/Vista.obj

# target to build an object file
Vista/Vista.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/Vista.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/Vista.cpp.obj
.PHONY : Vista/Vista.cpp.obj

Vista/Vista.i: Vista/Vista.cpp.i
.PHONY : Vista/Vista.i

# target to preprocess a source file
Vista/Vista.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/Vista.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/Vista.cpp.i
.PHONY : Vista/Vista.cpp.i

Vista/Vista.s: Vista/Vista.cpp.s
.PHONY : Vista/Vista.s

# target to generate assembly for a file
Vista/Vista.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/Vista.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/Vista.cpp.s
.PHONY : Vista/Vista.cpp.s

Vista/VistaParticipante.obj: Vista/VistaParticipante.cpp.obj
.PHONY : Vista/VistaParticipante.obj

# target to build an object file
Vista/VistaParticipante.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/VistaParticipante.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/VistaParticipante.cpp.obj
.PHONY : Vista/VistaParticipante.cpp.obj

Vista/VistaParticipante.i: Vista/VistaParticipante.cpp.i
.PHONY : Vista/VistaParticipante.i

# target to preprocess a source file
Vista/VistaParticipante.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/VistaParticipante.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/VistaParticipante.cpp.i
.PHONY : Vista/VistaParticipante.cpp.i

Vista/VistaParticipante.s: Vista/VistaParticipante.cpp.s
.PHONY : Vista/VistaParticipante.s

# target to generate assembly for a file
Vista/VistaParticipante.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Blackjack.dir\build.make CMakeFiles/Blackjack.dir/Vista/VistaParticipante.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/Vista/VistaParticipante.cpp.s
.PHONY : Vista/VistaParticipante.cpp.s

tests/test_blackjack.obj: tests/test_blackjack.cpp.obj
.PHONY : tests/test_blackjack.obj

# target to build an object file
tests/test_blackjack.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/tests/test_blackjack.cpp.obj
.PHONY : tests/test_blackjack.cpp.obj

tests/test_blackjack.i: tests/test_blackjack.cpp.i
.PHONY : tests/test_blackjack.i

# target to preprocess a source file
tests/test_blackjack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/tests/test_blackjack.cpp.i
.PHONY : tests/test_blackjack.cpp.i

tests/test_blackjack.s: tests/test_blackjack.cpp.s
.PHONY : tests/test_blackjack.s

# target to generate assembly for a file
tests/test_blackjack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tests.dir\build.make CMakeFiles/Tests.dir/tests/test_blackjack.cpp.s
.PHONY : tests/test_blackjack.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... Blackjack
	@echo ... Tests
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
	@echo ... Controlador/Controlador.obj
	@echo ... Controlador/Controlador.i
	@echo ... Controlador/Controlador.s
	@echo ... Modelo/Apuesta.obj
	@echo ... Modelo/Apuesta.i
	@echo ... Modelo/Apuesta.s
	@echo ... Modelo/Carta.obj
	@echo ... Modelo/Carta.i
	@echo ... Modelo/Carta.s
	@echo ... Modelo/Crupier.obj
	@echo ... Modelo/Crupier.i
	@echo ... Modelo/Crupier.s
	@echo ... Modelo/Jugador.obj
	@echo ... Modelo/Jugador.i
	@echo ... Modelo/Jugador.s
	@echo ... Modelo/Mazo.obj
	@echo ... Modelo/Mazo.i
	@echo ... Modelo/Mazo.s
	@echo ... Modelo/Participante.obj
	@echo ... Modelo/Participante.i
	@echo ... Modelo/Participante.s
	@echo ... Modelo/main.obj
	@echo ... Modelo/main.i
	@echo ... Modelo/main.s
	@echo ... Vista/Vista.obj
	@echo ... Vista/Vista.i
	@echo ... Vista/Vista.s
	@echo ... Vista/VistaParticipante.obj
	@echo ... Vista/VistaParticipante.i
	@echo ... Vista/VistaParticipante.s
	@echo ... tests/test_blackjack.obj
	@echo ... tests/test_blackjack.i
	@echo ... tests/test_blackjack.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

